#!/usr/bin/env python3
"""
emami_helper.py

Builds EMAMI_CLUSTER_EVIDENCE.csv from manually-transcribed extracts of
Emami Realty Ltd SEBI Reg.23(9) Related Party Transaction (RPT) disclosure
PDFs. All entity names below were read verbatim (via text-extraction proxy
r.jina.ai over the published PDF, since the PDFs are OCR'd scanned images
that standard PDF text extraction could not parse) from the source
documents listed in DOCS. Nothing here is invented; entities not actually
confirmed present in a given document are simply omitted for that document.
"""

import csv

OUT_PATH = "/home/user/claude/A3_ABSENT_LANE/cloud_blocks/EMAMI_CLUSTER_EVIDENCE.csv"

SECTION_HEADING = "Entities wherein the Company's promoters have significant influence"

DOC_A = {
    "url": "https://emamirealty.com/wp-content/uploads/2022/07/ERL-RPT-Disclosure-March-2021.pdf",
    "title": "Emami Realty Limited - Related Party Transactions Disclosure (Reg. 23(9) SEBI LODR)",
    "period": "Year ended 31 March 2021",
    "status": "FETCHED",
}

DOC_B = {
    "url": "https://emamirealty.com/wp-content/uploads/2023/01/ERL-RPT-Disclosure-Sep-2021.pdf",
    "title": "Emami Realty Limited - Related Party Transactions Disclosure (Reg. 23(9) SEBI LODR)",
    "period": "Half-year ended 30 September 2021",
    "status": "FETCHED",
}

DOC_C = {
    "url": "https://emamirealty.com/wp-content/uploads/2022/12/ERL_RPT-Disclosure_30.09.2022.pdf",
    "title": "Emami Realty Limited - Related Party Transactions Disclosure (Reg. 23(9) SEBI LODR)",
    "period": "Half-year ended 30 September 2022",
    "status": "FETCHED",
}

DOC_D = {
    "url": "https://emamirealty.com/wp-content/uploads/2022/07/ERL-RPT-Disclosure_31.03.2022.pdf",
    "title": "Emami Realty Limited - Related Party Transactions Disclosure (Reg. 23(9) SEBI LODR)",
    "period": "Half-year ended 31 March 2022",
    "status": "FETCHED",
}

# ---------------------------------------------------------------------------
# DOC A: full verbatim list, serials 1-226 (year ended 31 March 2021)
# ---------------------------------------------------------------------------
DOC_A_ENTITIES = [
(1,"Add Albatross Properties Private Limited"),
(2,"AMRI Hospitals Limited"),
(3,"Creative Cultivation Private Limited"),
(4,"Emami Agrotech Limited"),
(5,"Fastgrow Beverages Private Limited"),
(6,"Supervalue Buildcon Private Limited"),
(7,"Emami Cement Limited (upto 14.07.2020)"),
(8,"Supervalue Constructions Private Limited"),
(9,"Emami Estates Private Limited"),
(10,"Emami Home Private Limited"),
(11,"Emami Limited"),
(12,"Emami Power Limited (upto 28.03.2020)"),
(13,"Supervalue Projects Private Limited"),
(14,"Fastgrow Nirman Private Limited"),
(15,"Emami Vriddhi Commercial Private Limited"),
(16,"Fastgrow Crops Private Limited"),
(17,"Jhansi Properties Private Limited"),
(18,"Magnificient Vyapaar LLP"),
(19,"Midkott Trades Private Limited"),
(20,"New Way Constructions Limited"),
(21,"Oriental Sales Agencies (India) Private Limited"),
(22,"Paradise Agriculture Private Limited"),
(23,"Prime Constructions Private Limited"),
(24,"Sanjeevani Vyapaar LLP"),
(25,"Sneha Skyhigh Private Limited"),
(26,"Sneha Abasan Private Limited"),
(27,"Sneha Niketan Private Limited"),
(28,"Sundew Finance Private Limited"),
(29,"South City Projects (Kolkata) Limited"),
(30,"Anamika Kala Sangam Trust"),
(31,"Begonia Textiles Private Limited"),
(32,"Eveningstar Vinimay Private Limited"),
(33,"Polpit Vincom Private Limited"),
(34,"Satyam Housing Nieman Private Limited"),
(35,"Everline Abasan LLP"),
(36,"Everline Avas LLP"),
(37,"Everline Buildcon LLP"),
(38,"Everline Builders LLP"),
(39,"Everline Conclave LLP"),
(40,"Everline Constech LLP"),
(41,"Everline Construction LLP"),
(42,"Everline Enclave LLP"),
(43,"Everline Estates LLP"),
(44,"Everline Highrise LLP"),
(45,"Everline Homes LLP"),
(46,"Everline Niketan LLP"),
(47,"Everline Nirman LLP"),
(48,"Everline Promoters LLP"),
(49,"Everline Residency LLP"),
(50,"Everline Towers LLP"),
(51,"Everline Villa LLP"),
(52,"Fast Home Amenities LLP"),
(53,"Fast Home Atmosphere LLP"),
(54,"Fast Home Constech LLP"),
(55,"Fast Home Creative LLP"),
(56,"Fast Home Designs LLP"),
(57,"Fast Home Developers LLP"),
(58,"Fast Home Dimensions LLP"),
(59,"Fast Home Enclave LLP"),
(60,"Fast Home Galaxy LLP"),
(61,"Fast Home Highrise LLP"),
(62,"Fast Home Iconic LLP"),
(63,"Fast Home Niketan LLP"),
(64,"Fast Home Paradise LLP"),
(65,"Fastgrow Amenities LLP"),
(66,"Fastgrow Avas LLP"),
(67,"Fastgrow Avenues LLP"),
(68,"Fastgrow Bricks LLP"),
(69,"Fastgrow Buildcon LLP"),
(70,"Fastgrow Buildings LLP"),
(71,"Fastgrow Citylights LLP"),
(72,"Fastgrow Concrete LLP"),
(73,"Fastgrow Connect LLP"),
(74,"Fastgrow Constech LLP"),
(75,"Fastgrow Designs LLP"),
(76,"Fastgrow Developers LLP"),
(77,"Fastgrow Dream Home LLP"),
(78,"Fastgrow Dwelling LLP"),
(79,"Fastgrow Elite Property LLP"),
(80,"Fastgrow Empire LLP"),
(81,"Fastgrow Galaxy LLP"),
(82,"Fastgrow Greenview LLP"),
(83,"Fastgrow Heritage LLP"),
(84,"Fastgrow Home Constructions LLP"),
(85,"Fastgrow Iconic LLP"),
(86,"Fastgrow Landmark LLP"),
(87,"Fastgrow Legacy LLP"),
(88,"Fastgrow Lighthouse LLP"),
(89,"Fastgrow Living LLP"),
(90,"Fastgrow Lodging LLP"),
(91,"Fastgrow Luxe Living LLP"),
(92,"Fastgrow Majestic LLP"),
(93,"Fastgrow Modern Realty LLP"),
(94,"Fastgrow Nest LLP"),
(95,"Fastgrow Niketan LLP"),
(96,"Fastgrow Northwood LLP"),
(97,"Fastgrow Residency LLP"),
(98,"Fastgrow Residential LLP"),
(99,"Fastgrow Skytowers LLP"),
(100,"Fastgrow Smart Homes LLP"),
(101,"Fastgrow Sweet Living LLP"),
(102,"Fastgrow Township LLP"),
(103,"Fastgrow Ultima LLP"),
(104,"Fastgrow Urban LLP"),
(105,"Fastgrow Voyage Realty LLP"),
(106,"Home Citylights LLP"),
(107,"Prime Amenities LLP"),
(108,"Prime Appartments LLP"),
(109,"Prime Atmosphere LLP"),
(110,"Prime Avas LLP"),
(111,"Prime Conclave LLP"),
(112,"Prime Constech LLP"),
(113,"Prime Construction LLP"),
(114,"Prime Destinations LLP"),
(115,"Prime Dimensions LLP"),
(116,"Prime Eco-Builders LLP"),
(117,"Prime Ecospace LLP"),
(118,"Prime Fast Ashiyana LLP"),
(119,"Prime Fast Designs LLP"),
(120,"Prime Fast Enclave LLP"),
(121,"Prime Fast Galaxy LLP"),
(122,"Prime Fast Heritage LLP"),
(123,"Prime Fast Highrise LLP"),
(124,"Prime Fast Homes LLP"),
(125,"Prime Fast Housing LLP"),
(126,"Prime Fast Landmark LLP"),
(127,"Prime Fast Niketan LLP"),
(128,"Prime Fast Paradise LLP"),
(129,"Prime Fast Parkview LLP"),
(130,"Prime Fast Residency LLP"),
(131,"Prime Fast Residential LLP"),
(132,"Prime Fast Villa LLP"),
(133,"Prime Horizon LLP"),
(134,"Prime Lakeview LLP"),
(135,"Prime Niketan LLP"),
(136,"Prime Parkview LLP"),
(137,"Snowline Abasan LLP"),
(138,"Snowline Appartments LLP"),
(139,"Snowline Brick LLP"),
(140,"Snowline Buildcon LLP"),
(141,"Snowline Conclave LLP"),
(142,"Snowline Enclave LLP"),
(143,"Snowline Estates LLP"),
(144,"Snowline Highrise LLP"),
(145,"Snowline Homes LLP"),
(146,"Snowline Housing LLP"),
(147,"Snowline Niketan LLP"),
(148,"Snowline Nivas LLP"),
(149,"Snowline Promoters LLP"),
(150,"Snowline Properties LLP"),
(151,"Snowline Realtors LLP"),
(152,"Snowline Residency LLP"),
(153,"Snowline Towers LLP"),
(154,"Snowline Villa LLP"),
(155,"Supergrow Abasan LLP"),
(156,"Supergrow Amenities LLP"),
(157,"Supergrow Ashiyana LLP"),
(158,"Supergrow Buildings LLP"),
(159,"Supergrow Designs LLP"),
(160,"Supergrow Developers LLP"),
(161,"Supergrow Elite Properties LLP"),
(162,"Supergrow Enclave LLP"),
(163,"Supergrow Estate LLP"),
(164,"Supergrow Heritage LLP"),
(165,"Supergrow Infocom LLP"),
(166,"Supergrow Lodging LLP"),
(167,"Supergrow Modern Realty LLP"),
(168,"Supergrow Paradise LLP"),
(169,"Supergrow Villa LLP"),
(170,"Albatross Biocorp LLP"),
(171,"Viewline Abasan LLP"),
(172,"Viewline Ashiyana LLP"),
(173,"Viewline Buildcon LLP"),
(174,"Viewline Builders LLP"),
(175,"Viewline Constech LLP"),
(176,"Viewline Estates LLP"),
(177,"Viewline Heights LLP"),
(178,"Viewline Highrise LLP"),
(179,"Viewline Housing LLP"),
(180,"Viewline Niketan LLP"),
(181,"Viewline Projects LLP"),
(182,"Viewline Promoters LLP"),
(183,"Viewline Properties LLP"),
(184,"Viewline Residency LLP"),
(185,"Viewline Villa LLP"),
(186,"Supergrow Apartment LLP"),
(187,"Supergrow Avas LLP"),
(188,"Supergrow Avenues LLP"),
(189,"Supergrow Brick LLP"),
(190,"Supergrow Buildcon LLP"),
(191,"Supergrow Citylights LLP"),
(192,"Supergrow Commodeal LLP"),
(193,"Supergrow Conclave LLP"),
(194,"Supergrow Concrete LLP"),
(195,"Supergrow Connect LLP"),
(196,"Supergrow Constech LLP"),
(197,"Supergrow Creative LLP"),
(198,"Supergrow Dream Home LLP"),
(199,"Supergrow Dwelling LLP"),
(200,"Supergrow Empire LLP"),
(201,"Supergrow Galaxy LLP"),
(202,"Supergrow Highrise LLP"),
(203,"Supergrow Home Construction LLP"),
(204,"Supergrow Horizon LLP"),
(205,"Supergrow Housing LLP"),
(206,"Supergrow Iconic LLP"),
(207,"Supergrow Landmark LLP"),
(208,"Supergrow Legacy LLP"),
(209,"Supergrow Lifestyle LLP"),
(210,"Supergrow Lighthouse LLP"),
(211,"Supergrow Luxe Living LLP"),
(212,"Supergrow Majestic LLP"),
(213,"Supergrow Nest LLP"),
(214,"Supergrow Niketan LLP"),
(215,"Supergrow Nirman LLP"),
(216,"Supergrow Nivas LLP"),
(217,"Supergrow Northwood LLP"),
(218,"Supergrow Planner LLP"),
(219,"Supergrow Promoters LLP"),
(220,"Supergrow Residency LLP"),
(221,"Supergrow Resort LLP"),
(222,"Supergrow Shelter LLP"),
(223,"Supergrow Skytowers LLP"),
(224,"Supergrow Township LLP"),
(225,"Supergrow Ultima LLP"),
(226,"Superview Constructions Private Limited"),
]

# ---------------------------------------------------------------------------
# DOC B: full verbatim list, serials 1-323 (half-year ended 30 Sep 2021)
# Items 1-20 confirmed identical to Doc A opening; items 100-323 confirmed
# via direct re-extraction. Items 21-99 assumed identical ordering to Doc A
# (same list carried over half-year to half-year) EXCEPT WHERE THE
# RE-EXTRACTED RANGE (100-323) DIFFERS FROM DOC A -- those differences are
# real (this document adds an entire "Superfast ..." LLP block absent from
# Doc A, and re-numbers some entries). Only entities individually confirmed
# by direct extraction from THIS document are included below.
# ---------------------------------------------------------------------------
DOC_B_ENTITIES_1_20 = [
(1,"Add Albatross Properties Private Limited"),
(2,"AMRI Hospitals Limited"),
(3,"Creative Cultivation Private Limited"),
(4,"Emami Agrotech Limited"),
(5,"Fastgrow Beverages Private Limited"),
(6,"Supervalue Buildcon Private Limited"),
(7,"Emami Cement Limited"),
(8,"Supervalue Constructions Private Limited"),
(9,"Emami Estates Private Limited"),
(10,"Emami Home Private Limited"),
(11,"Emami Limited"),
(12,"Emami Power Limited (upto 28.03.2020)"),
(13,"Supervalue Projects Private Limited"),
(14,"Fastgrow Nirman Private Limited"),
(15,"Emami Vriddhi Commercial Private Limited"),
(16,"Fastgrow Crops Private Limited"),
(17,"Jhansi Properties Private Limited"),
(18,"Magnificient Vyapaar LLP"),
(19,"Midkot Trades Private Limited"),
(20,"New Way Constructions Limited"),
]

DOC_B_ENTITIES_100_323 = [
(100,"Fastgrow Smart Homes LLP"),
(101,"Fastgrow Sweet Living LLP"),
(102,"Fastgrow Township LLP"),
(103,"Fastgrow Ultima LLP"),
(104,"Fastgrow Urban LLP"),
(105,"Fastgrow Voyage Realty LLP"),
(106,"Home Citylights LLP"),
(107,"Prime Amenities LLP"),
(108,"Prime Appartments LLP"),
(109,"Prime Atmosphere LLP"),
(110,"Prime Avas LLP"),
(111,"Prime Conclave LLP"),
(112,"Prime Constech LLP"),
(113,"Prime Construction LLP"),
(114,"Superfast Amenities LLP"),
(115,"Superfast Anchor LLP"),
(116,"Superfast Appartments LLP"),
(117,"Superfast Ashiyana LLP"),
(118,"Superfast Atmosphere LLP"),
(119,"Superfast Attractive LLP"),
(120,"Superfast Avas LLP"),
(121,"Superfast Avenues LLP"),
(122,"Superfast Awasan LLP"),
(123,"Superfast Brick LLP"),
(124,"Superfast Buildcon LLP"),
(125,"Superfast Buildings LLP"),
(126,"Superfast Castel LLP"),
(127,"Superfast Citylights LLP"),
(128,"Superfast Commercial LLP"),
(129,"Superfast Commodeal LLP"),
(130,"Superfast Conclave LLP"),
(131,"Superfast Concrete LLP"),
(132,"Superfast Connect LLP"),
(133,"Superfast Constech LLP"),
(134,"Superfast Creative LLP"),
(135,"Superfast Dealtrade LLP"),
(136,"Superfast Deluxe LLP"),
(137,"Superfast Designs LLP"),
(138,"Superfast Devcon LLP"),
(139,"Superfast Developers LLP"),
(140,"Superfast Dimension LLP"),
(141,"Superfast Divine LLP"),
(142,"Superfast Dreamhome LLP"),
(143,"Superfast Dwelling LLP"),
(144,"Superfast Eco-Builders LLP"),
(145,"Superfast Ecospace LLP"),
(146,"Superfast Elite Properties LLP"),
(147,"Superfast Empire LLP"),
(148,"Superfast Enclave LLP"),
(149,"Superfast Estate LLP"),
(150,"Superfast Everline LLP"),
(151,"Superfast Everrise LLP"),
(152,"Superfast Exim LLP"),
(153,"Superfast Galaxy LLP"),
(154,"Superfast Goodshine LLP"),
(155,"Superfast Granite LLP"),
(156,"Superfast Greenview LLP"),
(157,"Superfast Heavens LLP"),
(158,"Superfast Heights LLP"),
(159,"Superfast Heritage LLP"),
(160,"Superfast Highrise LLP"),
(161,"Superfast Legacy LLP"),
(162,"Superfast Lifestyle LLP"),
(163,"Prime Destinations LLP"),
(164,"Prime Dimensions LLP"),
(165,"Prime Eco-Builders LLP"),
(166,"Prime Ecospace LLP"),
(167,"Prime Fast Ashiyana LLP"),
(168,"Prime Fast Designs LLP"),
(169,"Prime Fast Enclave LLP"),
(170,"Prime Fast Galaxy LLP"),
(171,"Prime Fast Heritage LLP"),
(172,"Prime Fast Highrise LLP"),
(173,"Prime Fast Homes LLP"),
(174,"Prime Fast Housing LLP"),
(175,"Prime Fast Landmark LLP"),
(176,"Prime Fast Niketan LLP"),
(177,"Prime Fast Paradise LLP"),
(178,"Prime Fast Parkview LLP"),
(179,"Prime Fast Residency LLP"),
(180,"Prime Fast Residential LLP"),
(181,"Prime Fast Villa LLP"),
(182,"Prime Horizon LLP"),
(183,"Prime Lakeview LLP"),
(184,"Prime Niketan LLP"),
(185,"Prime Parkview LLP"),
(186,"Snowline Abasan LLP"),
(187,"Snowline Appartments LLP"),
(188,"Snowline Brick LLP"),
(189,"Snowline Buildcon LLP"),
(190,"Snowline Conclave LLP"),
(191,"Snowline Enclave LLP"),
(192,"Snowline Estates LLP"),
(193,"Snowline Highrise LLP"),
(194,"Snowline Homes LLP"),
(195,"Snowline Housing LLP"),
(196,"Snowline Niketan LLP"),
(197,"Snowline Nivas LLP"),
(198,"Snowline Promoters LLP"),
(199,"Snowline Properties LLP"),
(200,"Snowline Realtors LLP"),
(201,"Snowline Residency LLP"),
(202,"Snowline Towers LLP"),
(203,"Snowline Villa LLP"),
(204,"Supergrow Abasan LLP"),
(205,"Supergrow Amenities LLP"),
(206,"Supergrow Ashiyana LLP"),
(207,"Supergrow Buildings LLP"),
(208,"Supergrow Designs LLP"),
(209,"Supergrow Developers LLP"),
(210,"Supergrow Elite Properties LLP"),
(211,"Supergrow Enclave LLP"),
(212,"Supergrow Estate LLP"),
(213,"Supergrow Heritage LLP"),
(214,"Supergrow Infocom LLP"),
(215,"Supergrow Lodging LLP"),
(216,"Supergrow Modern Realty LLP"),
(217,"Supergrow Paradise LLP"),
(218,"Supergrow Villa LLP"),
(219,"Albatross Biocorp LLP"),
(220,"Viewline Abasan LLP"),
(221,"Viewline Abasan LLP"),  # NOTE: source re-extraction repeated this line at the range boundary (220/221 overlap); kept verbatim as returned.
(222,"Viewline Ashiyana LLP"),
(223,"Viewline Buildcon LLP"),
(224,"Viewline Builders LLP"),
(225,"Viewline Constech LLP"),
(226,"Viewline Estates LLP"),
(227,"Viewline Heights LLP"),
(228,"Viewline Highrise LLP"),
(229,"Viewline Housing LLP"),
(230,"Viewline Niketan LLP"),
(231,"Viewline Projects LLP"),
(232,"Viewline Promoters LLP"),
(233,"Viewline Properties LLP"),
(234,"Viewline Residency LLP"),
(235,"Viewline Villa LLP"),
(236,"Supergrow Apartment LLP"),
(237,"Supergrow Avas LLP"),
(238,"Supergrow Avenues LLP"),
(239,"Supergrow Brick LLP"),
(240,"Supergrow Buildcon LLP"),
(241,"Supergrow Citylights LLP"),
(242,"Supergrow Commodeal LLP"),
(243,"Supergrow Conclave LLP"),
(244,"Supergrow Concrete LLP"),
(245,"Supergrow Connect LLP"),
(246,"Supergrow Constech LLP"),
(247,"Supergrow Creative LLP"),
(248,"Supergrow Dream Home LLP"),
(249,"Supergrow Dwelling LLP"),
(250,"Supergrow Empire LLP"),
(251,"Supergrow Galaxy LLP"),
(252,"Supergrow Highrise LLP"),
(253,"Supergrow Home Construction LLP"),
(254,"Supergrow Horizon LLP"),
(255,"Supergrow Housing LLP"),
(256,"Supergrow Iconic LLP"),
(257,"Supergrow Landmark LLP"),
(258,"Supergrow Legacy LLP"),
(259,"Supergrow Lifestyle LLP"),
(260,"Supergrow Lighthouse LLP"),
(261,"Supergrow Luxe Living LLP"),
(262,"Supergrow Majestic LLP"),
(263,"Supergrow Nest LLP"),
(264,"Supergrow Niketan LLP"),
(265,"Supergrow Nirman LLP"),
(266,"Supergrow Nivas LLP"),
(267,"Supergrow Northwood LLP"),
(268,"Supergrow Planner LLP"),
(269,"Supergrow Promoters LLP"),
(270,"Supergrow Residency LLP"),
(271,"Supergrow Resort LLP"),
(272,"Supergrow Shelter LLP"),
(273,"Supergrow Skytowers LLP"),
(274,"Supergrow Township LLP"),
(275,"Supergrow Ultima LLP"),
(276,"Superview Constructions Private Limited"),
(277,"Superfast Lighthouse LLP"),
(278,"Superfast Lodging LLP"),
(279,"Superfast Luxe Living LLP"),
(280,"Superfast Luxury LLP"),
(281,"Superfast Majestic LLP"),
(282,"Superfast Mansion LLP"),
(283,"Superfast Modern Realty LLP"),
(284,"Superfast Moonlink LLP"),
(285,"Superfast Nest LLP"),
(286,"Superfast Niketan LLP"),
(287,"Superfast Nirman LLP"),
(288,"Superfast Nivas LLP"),
(289,"Superfast Northwood LLP"),
(290,"Superfast Paradise LLP"),
(291,"Superfast Parkview LLP"),
(292,"Superfast Planner LLP"),
(293,"Superfast Pro-Estate LLP"),
(294,"Superfast Projects LLP"),
(295,"Superfast Promoters LLP"),
(296,"Superfast Realcon LLP"),
(297,"Superfast Realestate LLP"),
(298,"Superfast Regency LLP"),
(299,"Superfast Residency LLP"),
(300,"Superfast Resort LLP"),
(301,"Superfast Roserise LLP"),
(302,"Superfast Rosewood LLP"),
(303,"Superfast Shelter LLP"),
(304,"Superfast Skyscrapers LLP"),
(305,"Superfast Skytowers LLP"),
(306,"Superfast Terxim LLP"),
(307,"Superfast Tie Up LLP"),
(308,"Superfast Towers LLP"),
(309,"Superfast Township LLP"),
(310,"Superfast Trustworthy LLP"),
(311,"Superfast Ultima LLP"),
(312,"Superfast Unicom LLP"),
(313,"Superfast Unique LLP"),
(314,"Superfast Urban LLP"),
(315,"Superfast Villa LLP"),
(316,"Superfast Vintage LLP"),
(317,"Superfast Home Construction LLP"),
(318,"Superfast Horizon LLP"),
(319,"Superfast Housing LLP"),
(320,"Superfast Iconic LLP"),
(321,"Superfast Infocom LLP"),
(322,"Superfast Infra LLP"),
(323,"Superfast Infracon LLP"),
]

# ---------------------------------------------------------------------------
# DOC C (30.09.2022): entities individually confirmed present (not a full
# serial-by-serial transcription -- the source document runs to ~410 rows
# and the fetch tool summarised most of it). The distinct "Superfast ..."
# name-set was separately re-extracted in full (100 distinct names) via a
# targeted pass and is included in full below.
# ---------------------------------------------------------------------------
DOC_C_CONFIRMED_SAMPLE = [
    "Add Albatross Properties Private Limited",
    "Creative Cultivation Private Limited",
    "Emami Estates Private Limited",
    "Emami Home Private Limited",
    "Fastgrow Beverages Private Limited",
    "Fastgrow Crops Private Limited",
    "Fastgrow Nirman Private Limited",
    "Fastgrow Projects Private Limited",
]

DOC_C_SUPERFAST_FULL = [
"Superfast Abasan LLP","Superfast Advisory LLP","Superfast Amenities LLP","Superfast Anchor LLP",
"Superfast Appartments LLP","Superfast Ashiyana LLP","Superfast Atmosphere LLP","Superfast Attractive LLP",
"Superfast Avas LLP","Superfast Avenues LLP","Superfast Awasan LLP","Superfast Brick LLP",
"Superfast Buildcon LLP","Superfast Buildings LLP","Superfast Castel LLP","Superfast Citylights LLP",
"Superfast Commercial LLP","Superfast Commodeal LLP","Superfast Conclave LLP","Superfast Concrete LLP",
"Superfast Connect LLP","Superfast Constech LLP","Superfast Creative LLP","Superfast Dealtrade LLP",
"Superfast Deluxe LLP","Superfast Designs LLP","Superfast Devcon LLP","Superfast Developers LLP",
"Superfast Dimension LLP","Superfast Divine LLP","Superfast Dreamhome LLP","Superfast Dwelling LLP",
"Superfast Eco-Builders LLP","Superfast Ecospace LLP","Superfast Elite Properties LLP","Superfast Empire LLP",
"Superfast Enclave LLP","Superfast Estate LLP","Superfast Everline LLP","Superfast Everrise LLP",
"Superfast Exim LLP","Superfast Galaxy LLP","Superfast Goodshine LLP","Superfast Granite LLP",
"Superfast Greenview LLP","Superfast Heavens LLP","Superfast Heights LLP","Superfast Heritage LLP",
"Superfast Highrise LLP","Superfast Home Construction LLP","Superfast Horizon LLP","Superfast Housing LLP",
"Superfast Iconic LLP","Superfast Infocom LLP","Superfast Infra LLP","Superfast Infracon LLP",
"Superfast Landmark LLP","Superfast Legacy LLP","Superfast Lifestyle LLP","Superfast Lighthouse LLP",
"Superfast Lodging LLP","Superfast Luxe Living LLP","Superfast Luxury LLP","Superfast Majestic LLP",
"Superfast Mansion LLP","Superfast Modern Realty LLP","Superfast Moonlink LLP","Superfast Nest LLP",
"Superfast Niketan LLP","Superfast Nirman LLP","Superfast Nivas LLP","Superfast Northwood LLP",
"Superfast Paradise LLP","Superfast Parkview LLP","Superfast Planner LLP","Superfast Pro-Estate LLP",
"Superfast Projects LLP","Superfast Promoters LLP","Superfast Realcon LLP","Superfast Realestate LLP",
"Superfast Regency LLP","Superfast Residency LLP","Superfast Resort LLP","Superfast Roserise LLP",
"Superfast Rosewood LLP","Superfast Shelter LLP","Superfast Skyscrapers LLP","Superfast Skytowers LLP",
"Superfast Terxim LLP","Superfast Tie Up LLP","Superfast Towers LLP","Superfast Township LLP",
"Superfast Trustworthy LLP","Superfast Ultima LLP","Superfast Unicorn LLP","Superfast Unique LLP",
"Superfast Urban LLP","Superfast Villa LLP","Superfast Vintage LLP","Superfast Voyage Realty LLP",
]

# DOC D (31.03.2022): only individually confirmed entity is Fastgrow Crops
# Private Limited at serial 99; the fetch tool otherwise only summarised
# ranges without giving verbatim names, so nothing else from this document
# is asserted at entity-name granularity.
DOC_D_CONFIRMED = [
    (99, "Fastgrow Crops Private Limited"),
]


def build_rows():
    rows = []

    def add(entity, doc, section, verbatim, fetched="FETCHED"):
        rows.append({
            "ENTITY_NAME": entity,
            "DOC_URL": doc["url"],
            "DOC_TITLE": doc["title"],
            "DOC_PERIOD": doc["period"],
            "SECTION_HEADING": section,
            "VERBATIM_LINE": verbatim,
            "FETCHED_OR_SNIPPET": fetched,
        })

    for num, name in DOC_A_ENTITIES:
        add(name, DOC_A, SECTION_HEADING, f"{num}. {name}")

    for num, name in DOC_B_ENTITIES_1_20:
        add(name, DOC_B, SECTION_HEADING, f"{num}. {name}")
    for num, name in DOC_B_ENTITIES_100_323:
        add(name, DOC_B, SECTION_HEADING, f"{num}. {name}")

    for name in DOC_C_CONFIRMED_SAMPLE:
        add(name, DOC_C, SECTION_HEADING,
            f"(confirmed present, exact serial not captured) {name}")
    for name in DOC_C_SUPERFAST_FULL:
        add(name, DOC_C, SECTION_HEADING,
            f"(Superfast name-block, exact serial not captured) {name}")

    for num, name in DOC_D_CONFIRMED:
        add(name, DOC_D, SECTION_HEADING, f"{num}. {name}")

    return rows


def main():
    rows = build_rows()
    fieldnames = ["ENTITY_NAME", "DOC_URL", "DOC_TITLE", "DOC_PERIOD",
                  "SECTION_HEADING", "VERBATIM_LINE", "FETCHED_OR_SNIPPET"]
    with open(OUT_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    distinct_entities = sorted(set(r["ENTITY_NAME"] for r in rows))
    print(f"Wrote {len(rows)} rows to {OUT_PATH}")
    print(f"Distinct entity names: {len(distinct_entities)}")


if __name__ == "__main__":
    main()
